### Register User
POST http://localhost:8080/api/auth/register
X-Api-Key: Secret
Content-Type: application/json
Accept: application/json

{
  "username": "IpinTampan",
  "email": "IpinTampan@Gmail.com",
  "password": "Ipin123"
}

### Login
POST http://localhost:8080/api/auth/login
X-Api-Key: Secret
Content-Type: application/json
Accept: application/json

{
  "username": "IpinTampan",
  "password": "Ipin123"
}

### Logout
POST http://localhost:8080/api/auth/logout
X-Api-Key: Secret
Content-Type: application/json
Accept: application/json

{
  "token" : "80a361df-9338-4170-b94c-44d71852d5cd"
}

### get token to frontend
GET http://localhost:8080/api/auth/user
X-Api-Key: Secret
Authorization: Bearer 772aca36-910a-4c76-8a23-19fa8e52e3da

###create product
POST http://localhost:8080/api/products
X-Api-Key: Secret
Content-Type: application/json
Accept: application/json

{
  "id": 1,
  "name": "Lenovo Legion 5",
  "price": 300000,
  "quantity": 10
}

###create product invalid

POST http://localhost:8080/api/products
X-Api-Key: Secret
Content-Type: application/json
Accept: application/json

{
  "id" : "",
  "name": "",
  "price": 0,
  "quantity": -10
}
### get product
GET localhost:8080/api/products/A0010
X-Api-Key: Secret
Accept: application/json
### get product not found
GET localhost:8080/api/products/Salah
X-Api-Key: Secret
Accept: application/json

### Update Product
PUT localhost:8080/api/products/A0010
X-Api-Key: Secret
Content-Type: application/json
Accept: application/json

{
  "name": "Lenovo Legion 6 pro",
  "price": 100000,
  "quantity": 10

}
### Update Product not Found
PUT localhost:8080/api/products/Salah
X-Api-Key: Secret
Content-Type: application/json
Accept: application/json

{
  "name": "Lenovo Legion 6 pro",
  "price": 100000,
  "quantity": 10

}
### Update Product with invalid body
PUT localhost:8080/api/products/A001
X-Api-Key: Secret
Content-Type: application/json
Accept: application/json

{
  "name": "",
  "price": 0,
  "quantity": -10

}

### Delete product

DELETE localhost:8080/api/products/A0010
X-Api-Key: Secret
Accept: application/json

### Delete product not found
DELETE localhost:8080/api/products/A001
X-Api-Key: Secret
Accept: application/json

### list products
GET http://localhost:8080/api/products
X-Api-Key: Secret
### list products with size
GET http://localhost:8080/api/products?size=5
X-Api-Key: Secret
### list products with size and page
GET http://localhost:8080/api/products?size=5&page=1
X-Api-Key: Secret

### Create Purchase
POST http://localhost:8080/api/purchases
X-Api-Key: Secret
Content-Type: application/json
Accept: application/json

{
  "userId": 10,
  "productId": 1,
  "quantity": 2
}
### Get Purchase
GET http://localhost:8080/api/purchases?userId=10
X-Api-Key: Secret
Accept: application/json


### Initiate payment test
POST http://localhost:8080/api/payments/initiate
X-Api-Key: Secret
Content-Type: application/json
Accept: application/json

{
  "purchaseId": 9,
  "amount": 1000
}

### Confirm Payment
PUT http://localhost:8080/api/payments/confirm/3
X-Api-Key: Secret
Content-Type: application/json
Accept: application/json

{
  "status": "confirmed"
}

### Cancel Payment
PUT http://localhost:8080/api/payments/cancel/3
X-Api-Key: Secret
Content-Type: application/json
Accept: application/json

{
  "reason": "Customer request"
}

### get payment details
GET http://localhost:8080/api/payments/1
X-Api-Key: Secret
Accept: application/json

